version: '3'

services: 
    db: 
      container_name: fuseki-refibra
      hostname: fusekirefibra
      image: 'stain/jena-fuseki'
      environment: 
        ADMIN_PASSWORD: vini
      volumes:
        - db-data:/fuseki stain/jena-fuseki
      ports: 
        - "3030:3030"
      expose:
        - 3030
    web: 
      container_name: apicore-refibra
      hostname: apirefibra
      build: .
      container_name: apirefibra
      links:
        - db
      ports: 
        - "5000:80"

volumes:
  db-data: